### ISSUE TITLE
Is there any ETA on when ISR will be available?

### ISSUE THREAD

**Issue by rababahmed** [milliHQ/terraform-aws-next-js#154]
I'm varying my options between serverless-nextjs and tf-aws-nextjs, however my stack heavily relies on ISR. I really like the motivation behind this project and was hoping for an ETA if possible?

**Comment by ofhouse** [comment]
Hi, thanks for reaching out.

Wish I could provide an ETA on this feature but it's currently really difficult to say when I have time to work on it.
I already started research on this topic but it's not something that can be built during a weekend, since it requires a bigger extension of the existing architecture.

serverless-nextjs is therefore a more reliable choice at the time albeit their implementation has still some edge-cases that need some work (https://github.com/serverless-nextjs/serverless-next.js/issues/1098.

**Comment by rababahmed** [comment]
Hi, thanks for the update. Great work on this project, I'll keep an eye on updates.

**Comment by ofhouse** [comment]
I'm going to close this as a duplicate of #11.
This helps to find and focus on the active issues.
