### ISSUE TITLE
Host header in my SSR pages or APIs

### ISSUE THREAD

**Issue by Blue-Lamp** [milliHQ/terraform-aws-next-js#156]
When accessing the Host header in my SSR pages or APIs, I get an API Gateway domain instead of the CloudFront distribution or my domain name.

https://github.com/serverless-nextjs/serverless-next.js#when-accessing-the-host-header-in-my-ssr-pages-or-apis-i-get-an-s3-domain-instead-of-the-cloudfront-distribution-or-my-domain-name

**Comment by ofhouse** [comment]
Hi, thanks for the report.

Yes, we change the `host` header in the proxy component to match the host of the API Gateway.
This happens because we don't add custom domains to the API Gateway distribution and therefore the gateway would reject requests from foreign hosts.

Unfortunately we don't change the header back to the original host from the viewer before calling the Lambda which causes that the API or SSR pages see the internal API Gateway endpoint as host.

## Proposed solution:

 1. We add a new header [`x-forwarded-host`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-Host) in the proxy component that contains the original `host` header from the viewer when we change the `host` header to API Gateway endpoint.
 2. Before calling the Lambda (in [node-bridge](https://github.com/dealmore/terraform-aws-next-js/tree/main/packages/node-bridge)) we then replace the `host` header with the value from `x-forwarded-host`.

Will take a look soon 👍

**Comment by ofhouse** [comment]
This has now been fixed in [`v0.10.0`](https://github.com/milliHQ/terraform-aws-next-js/releases/tag/v0.10.0).
