### ISSUE TITLE
How about adding a sponsor button to this repository?

### ISSUE THREAD

**Issue by b6pzeusbc54tvhw5jgpyw8pwz2x6gs** [milliHQ/terraform-aws-next-js#215]
How about adding a sponsor button to this repository? like this:

![Screen Shot 2021-09-30 at 3 54 03 AM](https://user-images.githubusercontent.com/15520015/135331071-1e0bd199-ddb5-4b8d-aeff-15b59ecc4c40.png)

I don't know about the business model of this project, but I think there are people who would like to support it as a valuable open source project.

**Comment by ofhouse** [comment]
Thanks for the suggestion 👍
Making money from it is currently not the primary focus, since acquiring more users and maintainers for the project is more important for now.

I plan a more sustainable business model for it that is more focused on enterprise requirements.
Since Next.js is evolving faster than ever before (Vercel has massively increased the team size from the VC money they got), it will be important for the future of this project that it has more active maintainers to support new features as soon as they arrive.

While the module itself will stay free (including its components like the CLI) my plan is to build an enterprise offering on top of the module.
Since people that use this module are already familiar with the Hashicorp stack, the plan is to offer a paid [Waypoint](https://www.waypointproject.io/) plugin.
Instead of using the CLI for building & updating the stack this is then automated with a GitHub & GitLab integration offered by Waypoint.

There are still uncertainties tough, since Waypoint is currently not ready for primetime and the multi-deployments feature is also needed for this to happen.
We will see, plan is to ship an early version of the plugin by the end of the year. 😅
