### ISSUE TITLE
Workflow for updating the app code after initial deployment

### ISSUE THREAD

**Issue by a35026** [milliHQ/terraform-aws-next-js#232]
Thanks for the great tool! As a Terraform newbie I'm using the config identical to the repo readme  
It deploys the app correctly without any issues, everything works as expected
```terraform
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 3.0"
    }
  }
}

provider "aws" {
  region = "us-east-1"
}

provider "aws" {
  alias  = "global_region"
  region = "us-east-1"
}

module "tf_next" {
  source = "milliHQ/next-js/aws"

  providers = {
    aws.global_region = aws.global_region
  }
}

output "cloudfront_domain_name" {
  value = module.tf_next.cloudfront_domain_name
}
```
Then I change something in the app and try to redeploy using these commands
```sh
$ yarn tf-next
$ terraform apply
```
This redeploys the app without any thrown errors
```
module.tf_next.module.statics_deploy.null_resource.static_s3_upload[0]: Creation complete after 10s [id=6524032431818241869]
module.tf_next.aws_lambda_function.this["__NEXT_API_LAMBDA_0"]: Still modifying... [id=tf-next___NEXT_API_LAMBDA_0, 10s elapsed]
module.tf_next.aws_lambda_function.this["__NEXT_API_LAMBDA_0"]: Modifications complete after 13s [id=tf-next___NEXT_API_LAMBDA_0]

Apply complete! Resources: 1 added, 1 changed, 1 destroyed.
```
But I can't see any changes neither 5 minutes nor 12 hours after the deployment  

This is what I see in config.json inside the build directory
```json
"lambdas": {
  "__NEXT_API_LAMBDA_0": {
    "handler": "now__launcher.launcher",
    "runtime": "nodejs14.x",
    "filename": "lambdas/__NEXT_API_LAMBDA_0.zip",
    "route": "/__NEXT_API_LAMBDA_0"
  }
},
```
Could it be somehow connected to S3 not being able to detect changes due to the same zip filenames?

**Comment by a35026** [comment]
@ofhouse Just FYI that I can see the latest changes after invalidating CloudFront distribution using CLI  
Meaning that the question is how to automatically invalidate Cloudfront distribution using Terraform  
Is it even possible with Terraform or I should look into CI/CD tools for refreshing lambdas code?

**Comment by ofhouse** [comment]
Hi,
the way to redeploy your changes looks good.
For each redeploy an execution of the `yarn tf-next` and `terraform apply` command is required.
`yarn tf-next` builds the static files and the Lambdas from the actual source code.
`terraform apply then updates the Lambdas and uploads the static files to S3.

So the replacement of changed Lambdas is a task that is fulfilled by Terraform.
As I can see from the output
> ```plain
>module.tf_next.module.statics_deploy.null_resource.static_s3_upload[0]: Creation complete after 10s   [id=6524032431818241869]
>module.tf_next.aws_lambda_function.this["__NEXT_API_LAMBDA_0"]: Still modifying... [id=tf->next___NEXT_API_LAMBDA_0, 10s elapsed]
>module.tf_next.aws_lambda_function.this["__NEXT_API_LAMBDA_0"]: Modifications complete after 13s [id=tf-next___NEXT_API_LAMBDA_0]
>
>Apply complete! Resources: 1 added, 1 changed, 1 destroyed.
>```

The modification of the Lambda was successful.
The Lambdas are not cached. When the update is complete, the new version immediately starts serving incoming requests.

What could be cached however is the response from the Lambda.
Since every Response is piped through CloudFront it could be possible that incoming requests are served from the CloudFront cache instead of being served from the Lambda.


To check this you can go into the DevTools of your Browser and switch to the Network tab.
From there you can take a look at the response headers that CloudFront is adding to the response:
![Screenshot 2021-11-04 at 18 44 17](https://user-images.githubusercontent.com/472867/140391800-ad6dd87f-2557-4424-b5c5-02c1ee574440.png)

When the `age` header has a number greater `0` and `x-cache` is set to `Hit from cloudfront` this indicates that the request is served from the CloudFront cache rather than from the Lambda.

We currently only have the ability to invalidate static paths (that are served by S3 and not from Lambda).
So a complete CloudFront invalidation (`/*`) could be necessary after updating a Lambda.

**Comment by a35026** [comment]
Thanks for the prompt reply and thorough explanation!  
Yes, I was using the complete invalidation  
```
$ aws cloudfront create-invalidation --distribution-id E1Q6L7QP8MD7ID --paths "/*"
```
Thank you for the great tool that worked flawlessly from a first try (unlike serverless)!

**Comment by jatidevelopments** [comment]
> Thanks for the prompt reply and thorough explanation! Yes, I was using the complete invalidation
> 
> ```
> $ aws cloudfront create-invalidation --distribution-id E1Q6L7QP8MD7ID --paths "/*"
> ```
> 
> Thank you for the great tool that worked flawlessly from a first try (unlike serverless)!

Cheers! Made the deployment work with AWS Cloud9.
