### ISSUE TITLE
Single Cache Policy Name for multiple deployments

### ISSUE THREAD

**Issue by JT-Bruch** [milliHQ/terraform-aws-next-js#233]
### Context
We are using an ephemeral development strategy which means that each feature branch gets its own deployment.  Everything works great except there is a maximum cache policy limit of 20. 

I am deploying two NextJS apps, which means I get 4 cache policies per environment created.  As far as I can tell, they are identical, which the exception of their names.  I have associated a single policy to all the environments and everything seems to work fine.

### Question
Is there a plan/way to specify a single cache policy that can be reused between multiple distributions without having to manually create a whole new distribution?

### Other Approaches
I do have a support ticket out to AWS to see about service limit increases as well.

**Comment by ofhouse** [comment]
Yeah, the module is not really well suited for preview deployments at the moment.
We have an update for handling multiple deployments in the works, but it will probably take until next year until it's ready.

Honestly wasn't aware that the limit on CloudFront Policies is this low 🙈
The module with the current version 0.10.1 should only create 2 cache policies and 1 origin request policy per deployed instance.

Main problem here is the policy that is created from the [image optimizer module](https://github.com/milliHQ/terraform-aws-next-js-image-optimization) that is a submodule of this module.
Passing all these values up and down between the modules is something I want to avoid.

Don't know if you are using `next/image` in your project, otherwise you could disable the creation of the resources by passing `create_image_optimization  = false` to the module what would save at least 1 cache policy.

**Comment by JT-Bruch** [comment]
Thanks for the response! I definitely appreciate it and it makes total sense.  AWS ended up reaching out and you can increase the number of cache policies. I got them to up it to 100, which should be plenty for awhile.
