### ISSUE TITLE
Error: error deleting API Gateway v2 integration

### ISSUE THREAD

**Issue by rahulpatelct** [milliHQ/terraform-aws-next-js#247]
I am facing one issue while terraform apply. till 4-5 days, everything working as expected. I deployed my latest code changes today find this error. 

```
Error: error deleting API Gateway v2 integration: ConflictException: Cannot delete Integration because it is referenced by the following Routes with Ids: [xrfucl1]
```

Any clue why this happened? Seems due to route dependancies, not able to delete this resource.

**Comment by ofhouse** [comment]
Hi, never saw this error before.
Can you see in the AWS console the pathname of the route that cannot be deleted?

**Comment by aquanow-jeffen** [comment]
I am also seeing a similar issue when deploying my app today. And this my log and screenshot from aws.
```
module.tf_next.module.next_image[0].module.api_gateway.aws_apigatewayv2_integration.this["GET /_next/{proxy+}"]: Destroying... [id=wq2w79p]
╷
│ Error: error deleting API Gateway v2 integration: ConflictException: Cannot delete Integration because it is referenced by the following Routes with Ids: [npaqlgj]
│ 
│ 
╵
```
<img width="710" alt="image" src="https://user-images.githubusercontent.com/85473293/144148008-520456d0-99c2-42b9-ba12-c098b4f0ae4c.png">

**Comment by aquanow-jeffen** [comment]
I don't know the cause but manually deleting the integration from api-gateway seems to solve the issue. I can now deploy without errors.

**Comment by ofhouse** [comment]
Thanks for providing additional details.
Seems like this is related to the new release of the [image optimization submodule](https://github.com/milliHQ/terraform-aws-next-js-image-optimization).
We changed the internal naming of the resources (removed the random ids from it) and it seems like Terraform is trying to link the old routes to a new API-Gateway resource, instead of recreating the whole API-Gateway resource.

Needs some further investigation if we are able to fix this on our side, but when doing the manual deletion in the AWS console the error should not happen again (Since we don't plan to rename the resources anytime soon 😁).

**Comment by curtis-trynow-io** [comment]
@rahulpatelct I have had this happen at various times when making significant changes to the TF Next module's configuration.  My normal way to find the resources that need to be deleted so that TF Next can recreate them is:

1. Go into CloudFront and find the distro that matches what you are working on by alternate (CNAME) name config.
2. Go to the Origins screen, find the execute API endpoint for the image optimizer.
3. Go to API Gateway and search by that endpoint and open it up.
4. Go to Integrations, open the related Lambda function, and delete the function entirely; I have never had Terraform succeed if the function still exists.
5. Go to Routes and delete the route.
6. Rerun Terraform apply command.

And TF will rebuild the resources appropriately.

**Comment by ofhouse** [comment]
I'm going to close this issue because it has been inactive for 30 days ⏳. This helps to find and focus on the active issues.
