### ISSUE TITLE
Request to update 1.0.0-canary.2

### ISSUE THREAD

**Issue by khuezy** [milliHQ/terraform-aws-next-js#252]
Hi, thanks for this project. I want to try out the `multiple_deployments` flag using the latest `1.0.0-canary.1` build but I'm getting:

"This object does not have an attribute named "cloudfront_origin_image_optimizer". I believe that fix hasn't been picked into the canary release.

Is there a way around this or do I just need to wait for an update.
Thanks!

EDIT: nvm I can edit the `main.tf` inside `.terraform`. Would be nice to get this fixed though.

**Comment by ofhouse** [comment]
Hey,

I will try to push an updated version by the end of the week. 👍

**Comment by ofhouse** [comment]
Applied a pretty big rebase on it (to sync it with the current main branch).
So I have to test it first before releasing a new prerelease version.

**Comment by khuezy** [comment]
Awesome thanks! @ofhouse Do you think this atomic deployment will fix the issue https://github.com/milliHQ/terraform-aws-next-js/issues/284?

**Comment by ofhouse** [comment]
No, this is unrelated to the atomic deployment feature.
This will probably be fixed with #86 and/or #11.

Since Vercel has open sourced their builder scripts for Next.js again, I will likely drop our fork (`packages/runtime`) of it that is now ~1.5 years old and use their updated builder instead.
So my hope is that switching to the server target resolves some issues with newer versions of Next.js.
