### ISSUE TITLE
[Question] What happens on a failed provision/deploy?

### ISSUE THREAD

**Issue by joecritch** [milliHQ/terraform-aws-next-js#257]
Hi, I'm trying to evaluate this library for use instead of AWS Amplify Hosting (which I can no longer use, due to client requirements).

Please can you help me understand what the module does during `terraform apply`? I noticed that it seems to destroy existing resources during this process, so if it then fails after these steps, does it leave the previous deployment in a broken state? 

(Perhaps I'm misunderstanding what these destroyed resources are, but I'm looking for something that works more like Amplify, where a failed CI/CD can't easily break the previous deployment.)

**Comment by khuezy** [comment]
Hi, I'm no means a terraform expert so I could be wrong, but I don't believe terraform destroys any existing resources when you run `terraform apply`.

When you run `terraform plan` or `terraform apply`, you should get a list of additions (+), deletions (-), or changes (~). So as long as you didn't add or remove any modules/providers in your `.tf` file, you shouldn't difference.

What terraform does is ping the provider (aws in this case) and queries about the state of your resources and adds/removes/updates them accordingly to your topography. ie, if a resource already exists, it doesn't destroy and recreate... it skips it. You should see "No changes" when you run `terraform plan`.

If you run `apply` and it fails (due to any aws reason), terraform will abort and will not cleanup any resources. You'll need to run `terraform destroy` to clean up.
If you made changes to the config (eg setting a bad subnet value) and `apply` fails, terraform does not automatically revert to the last successful state. You'll need to revert your `.tf` change and reapply.

**Comment by ofhouse** [comment]
As already mentioned, Terraform does not destroy or modify any resources that are created outside of Terraform (e.g. resources that are created through the web console).

Instead Terraform crates a state file where all created resources are referenced by unique IDs, to keep track of the resources it has created in the past.
All resources in the state file are considered as resources that are under Terraforms's control and can be modified or deleted when running `terraform apply`.
If you want to have more control what Terraform modified, adds or deletes, `terraform plan` shows you a diff to your current deployment without applying the changes.

Our module currently does not support atomic deployments. So when updating your Next.js app, the current deployment is modified to match the updated app.
This can result in destruction and recreation of resources that were created in previous deployments (We try to keep this minimal and only modify resources that can handle updates immediately to keep deployment times low)

If a deployment fails this could lead to a broken application, that must be recovered by redeploying an updated or previous state of the app.
Best practice would be here to setup a dev/testing/production deployment to minimize the risk of breaking the app in production.

**Comment by khuezy** [comment]
Hey @ofhouse , can you provide an example of the dev/testing/production deployment? Is this the same as the `multiple_deployment` feature on your road map?

Or can you just pass in an `env` `-var` to the cli as the deployment name?
eg: `deployment_name: "tf-next-${env}"

**Comment by joecritch** [comment]
Thanks to both of you for this knowledge bomb! :D Also curious on the above ^

**Comment by khuezy** [comment]
@joecritch https://www.hashicorp.com/blog/zero-downtime-updates-with-terraform
 Certain resources may be destroyed and recreated, so perhaps that's what you were seeing.

Applying solution 1 and 2 is a good idea.

**Comment by ofhouse** [comment]
> Is this the same as the multiple_deployment feature on your road map?

No, the multiple deployments feature will work similar to atomic deployments on Vercel.
So environments are created dynamically there rather than statically with Terraform.

> Can you provide an example of the dev/testing/production deployment?

Probably a topic that should be covered in a blog post, but to give you an idea how to do that:

1. Create a file structure similar to this pattern:
    ```
    terraform/
    ├── env/
    │   ├── production/
    │   │   └── main.tf
    │   ├── testing/
    │   │   └── main.tf
    │   └── development/
    │       └── main.tf
    └── modules/
        └── app/
            └── main.tf
    ```
   
2. The `app` module is the main module that contains the whole deployment:
    ```terraform
    # terraform/modules/app/main.tf
    
    variable "deployment_name" {
      type = string
    }
    
    module "tf_next" {
      source = "milliHQ/next-js/aws"

      deployment_name = "my-app_${var.deployment_name}"
      ...
    }
   ```
    
3.  Each stage gets another module that is located in the `env/` folder, e.g. for development:
    ```terraform
    # terraform/env/development/main.tf
    
    module "app" {
      # Import the app module here, and set environment specific variables
      source = "../../modules/app"
    
      deployment_name = "development"
    }
    ```

4. Run `terraform apply` from the environment directory for each stage.
    E.g. to deploy development, run `terraform apply` from the `terraform/env/development` directory.

**Comment by mbaranovski** [comment]
Thank you @ofhouse for the example above! If someone is using a terraform backend (S3 for instance), I think that before each stage deployment (dev/test/prod) one need to create/select a new terraform workspace. Am I right?

Also, is there anyway to check the progress on multiple deployments or maybe contribute somehow? Thanks!

**Comment by ofhouse** [comment]
@mbaranovski Yes, different deployment stages currently have to be created upfront due to the static nature of Terraform deployments.

I am currently working on breaking up with this limitation and making deployments independent from the Terraform configuration.
The main idea ist laid out here: #295.
Currently making good progress on this and the plan is to release a prototype of this within the next 3 weeks.
