### ISSUE TITLE
[Question] add security headers on cloudfront response?

### ISSUE THREAD

**Issue by aquanow-jeffen** [milliHQ/terraform-aws-next-js#262]
Hi, I have been using this module to deploy my project to production for some time and we have a requirement to add security headers to every page response. Currently what I'm doing is adding the header through `getServerSideProps`, which have a page loading speed overhead. I am aware there is a ticket in the backlog about adding support for it. But do you know if there is any way I can add it from the infrastructure side, do you recommend if I provide my own CloudFront module through CloudFront function or edge function?

Thank you very much!

**Comment by ofhouse** [comment]
If the content of the header is static I probably would recommend using [CloudFront response headers policies](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/adding-response-headers.html) for it.

Another way would be to add a [CloudFront function](https://aws.amazon.com/blogs/aws/introducing-cloudfront-functions-run-your-code-at-the-edge-with-low-latency-at-any-scale/) that adds the headers to the response.

This is not supported by the internal CloudFront distribution, so before applying one of these, the CloudFront distribution should be outsources following the [with existing CloudFront distribution example](https://github.com/milliHQ/terraform-aws-next-js/tree/main/examples/with-existing-cloudfront).

**Comment by aquanow-jeffen** [comment]
Thanks for replying! I also would like to get some thoughts on the migration plan.
Terraform probably won't let me migrate the existing auto-generated CloudFront to outsourced without downtime? I'd imagine it will destroy auto-generated one because it should be managed by tf-next module.
I think I probably need to create a new CloudFront distribution, apply, and then replace auto-generated with newly created one right?

**Comment by ofhouse** [comment]
> Terraform probably won't let me migrate the existing auto-generated CloudFront to outsourced without downtime? I'd imagine it will destroy auto-generated one because it should be managed by tf-next module.

Yeah, that would be the default behavior and would result in probably ~30min downtime, since the Lambda@Edge needs to be detached and reattached to the new CloudFront (Detaching can take up to 30min).
Also when using a custom domain there can also AWS wide only one CloudFront distribution that is associated with the domain. So you have to wait until the existing distribution is deleted, before deploying the new one.
So I would not recommend going this way.

Fortunately the latest Terraform 1.1 release introduced a [new way to migrate and refactor resources](https://www.hashicorp.com/blog/terraform-1-1-improves-refactoring-and-the-cloud-cli-experience) between modules.
Using the new `moved` statements you should be able to move & update the distribution without recreating it: https://www.terraform.io/language/modules/develop/refactoring#splitting-one-module-into-multiple

**Comment by aquanow-jeffen** [comment]
I tried to use `moved` block refactor my infrastructure yesterday but wasn't successful. Might because I couldn't move a resource from remote module or it's a bit too complicated to handle? And I also a little concern about outsourced cloudfront will get more discrepancy over time when this project adding features and configs.

Would it be ok if I open a PR adding variable `response_headers_policy_id`  just like `cloudfront_origin_request_policy`?

**Comment by ofhouse** [comment]
Unfortunately I never worked with the `moved` blocks before, so I would need to check it out by myself what prevents Terraform from moving the resource correctly.
Currently reworking the website, I will add this topic (moving from internal to external CloudFront distribtuion) as a potential guide topic to the backlog.

> Would it be ok if I open a PR adding variable `response_headers_policy_id` just like `cloudfront_origin_request_policy`?

Yes, would accept an PR on this, since we don't use this policy and could provide a good workaround until I find out how to handle #9. 👍
