### ISSUE TITLE
[Question] dotenv

### ISSUE THREAD

**Issue by exodusanto** [milliHQ/terraform-aws-next-js#272]
Hi,

I'm using terraform with workspaces, for multiple `.env` files the tf-module have some configuration to handle it or it use the default `.env` and in my deploy pipeline I have to move the `.env.staging` to `.env`?

The second question is about `lambda_environment_variables`, if there is a `.env` this variable map is also needed or is redundant for the lambda function?

Thanks!

**Comment by ofhouse** [comment]
Not sure if It understood correctly: Neither the module or Terraform itself has native support for `.env` files.
However you could create a map from [reading a `.env`](https://stackoverflow.com/a/67653301/831465) like this:

```tf
locals {
  env_vars = { for tuple in regexall("(.*)=(.*)", file("/path/to/.env")) : tuple[0] => tuple[1] }
}

module "tf_next" {
  source = "milliHQ/next-js/aws"
  ...

  lambda_environment_variables = local.env_vars
}
```

**Comment by exodusanto** [comment]
This question has arisen to me cause in Cloudwatch Logs before `START` log there always be `Loading .env` and adding `.env.staging` it output two logs `Loading .env` and `Loading .env.staging` so I though that is a sort of `tf_next` module options.

Probably it's a feature of lambda and the `.env` is added to the deploy Zip.

Back to the question, according to your reply this `.env` loading was not intended as a _tf_next_ feature, and to load env vars to lambda you have to use that `lambda_environment_variables` input parameter.

**Comment by ofhouse** [comment]
> Probably it's a feature of lambda to load dotenv files if inside the deploy and the `.env` is added to the deploy Zip.

No, this is a feature from Next.js's package [`next-env`](https://github.com/vercel/next.js/tree/canary/packages/next-env).
So yeah, it seems like the `.env` files are bundled to the deploy zip if there are any and then loaded by Next.js during the Lambda invoke.

> Back to the question, according to your reply this `.env` loading was not intended as a _tf_next_ feature, and to load env vars to lambda you have to use that `lambda_environment_variables` input parameter.

Actually it seems like there are multiple ways to load environment variables. 😅
1. The one that uses `.env` files comes from Next.js itself, which sets the environment variable to a fixed value during **build time** (when running `tf-next build`) since the `.env` file is checked into the zip as a static file.
2. When using `lambda_environment_variables` the environment variable is set during **runtime** (every time a Lambda is invoked) by AWS Lambda platform.

_(Note that environment variables that are set using `lambda_environment_variables` override environment variables that are set via `.env`, since dotenv does not override existing environment variables, and environment variables from Lambda platform are loaded earlier than dotenv)_

So if you need a maximum of flexibility I would recommend using option 2 to set environment variables, but if you have default values or variables that don't change often, using `.env` for them also seems like a fine option too.
