### ISSUE TITLE
404 error when S3 Server Side encryption is enabled

### ISSUE THREAD

**Issue by sumantapakira** [milliHQ/terraform-aws-next-js#279]
I am using your great work in our project. Thanks for putting this. 
Our NextJS application or your Sample NextJS app is deployed and working fine. But in our AWS environment, Security Hub complains that S3 buckets which are created as part of this deployment are using default encryption. 
So to fix this issue, I have changed to server encryption in terraform code. Steps I have followed-
1. Clone your github repo
2. In NextJS app, changed the main.tf from `source = "milliHQ/next-js/aws"` to `source = "my-local-repo"`
3. Added the below code in this file /modules/static-deploy/main.tf

       server_side_encryption_configuration {
       rule {
         apply_server_side_encryption_by_default {
         kms_master_key_id = aws_kms_key.mykey.arn
         sse_algorithm     = "aws:kms"
          }
         }
       }

Inside resource "aws_s3_bucket" "static_upload" and resource "aws_s3_bucket" "static_deploy" 

4. Also did the same in this file /modules/cloudfront-proxy-config inside the resource "aws_s3_bucket" "proxy_config_store" 

After deploying this when I hit the app url then I get 404 page from default Nextjs app

When I use AWS default encryption then it works.

Could you please help me? 

Best regards,
Pakira

**Comment by ofhouse** [comment]
Hi,

would generally not recommend to enable encryption for the S3 buckets generated by the module.
Most of the content in the S3 buckets is exposed publicly through CloudFront, so saving them encrypted does not add any additional security.
Instead it increases costs and latency for each S3 request, since the AWS keystore is hit for each request.

Never worked with encrypted buckets before, but your approach seems fine.
Have you checked the content of the S3 bucket in the web console, if the requested file still exists there?

**Comment by sumantapakira** [comment]
Yes, all the files are present there, I think the custom key which I am using does not have proper permission. I will close this issue.
