### ISSUE TITLE
Question: Config Option for connecting to AWS Aurora?

### ISSUE THREAD

**Issue by amir-beheshty** [milliHQ/terraform-aws-next-js#283]
My nextjs app uses PostgreSQL database and I'm curious to know if you have plans to add database migration/connection to the configurations? Something similar to what [vercel offers](https://vercel.com/guides/nextjs-prisma-postgres).

**Comment by ofhouse** [comment]
Hi,
integrating a whole database solution into the module would be out of scope of this project.
However the module can be integrated into a larger Terraform configuration that also includes a connection to a database (e.g. RDS or Aurora).

We currently don't offer an explicit example project for this use case. But since the Vercel guide simply uses [Prisma](https://www.prisma.io/) for connection and a public RDS instance as database you should be able to follow the most parts of it.
At the end instead of deploying it to Vercel you can then use the Terraform module to deploy the Next.js app to AWS.

**Comment by ofhouse** [comment]
I'm going to close this issue because it has been inactive for 30 days ⏳. This helps to find and focus on the active issues.
