### ISSUE TITLE
Support for Node v16

### ISSUE THREAD

**Issue by anudit** [milliHQ/terraform-aws-next-js#315]
Could we upgrade `@vercel/build-utils` to `2.17.0` from [`2.12.1`](https://github.com/milliHQ/terraform-aws-next-js/blob/751098478d9dbdfa657e40b0e33fb5436e01f1b9/packages/tf-next/package.json#L23) to support the new Node 16 runtime?

Running into the following error currently,
![image](https://user-images.githubusercontent.com/12015553/168588738-30d5af57-3f37-4921-8a3a-598d4d91e157.png)

**Comment by ofhouse** [comment]
Hi, yes Node 16 runtime support is on the radar, but takes a few extra steps besides just upgrading the `@vercel/build-utils` dependecy:

- Upgrade sammy: https://github.com/milliHQ/sammy/issues/13

**Comment by ofhouse** [comment]
Oh, misinterpreted your issue.
You are asking for Node.js 16 support for the CLI not the `nodejs16.x` runtime 🙈

**Comment by ofhouse** [comment]
However I think setting the `"engines": { "node": "14.x" }` field in your `package.json` is the right solution here.
The CLI should still build fine with Node.js 16, but since we currently don't support the `nodejs16.x` runtime, it does not make sense to allow the creation of Lambdas with Node.js 16 as target.

**Comment by ofhouse** [comment]
This has been fixed in [`v0.13.0`](https://github.com/milliHQ/terraform-aws-next-js/releases/tag/v0.13.0).
