### ISSUE TITLE
Support for nodejs16.x runtime

### ISSUE THREAD

**Issue by ofhouse** [milliHQ/terraform-aws-next-js#316]
## ToDo:

- Upgrade sammy: https://github.com/milliHQ/sammy/issues/13
- Upgrade `@vercel/build-utils`
- Set default runtime to `nodejs16.x` in `variables.tf`
- (blocked) Wait for Terraform AWS Provider `v4.15.0` to be released (https://github.com/hashicorp/terraform-provider-aws/issues/24714, https://github.com/hashicorp/terraform-provider-aws/pull/24768)

**Comment by larahroth** [comment]
Hi! :D We are using your lovely library and noticed that [edge functions now support node 16](https://docs.amazonaws.cn/en_us/AmazonCloudFront/latest/DeveloperGuide/edge-functions-restrictions.html). 

> However I think setting the "engines": { "node": "14.x" } field in your package.json is the right solution here.
The CLI should still build fine with Node.js 16, but since we currently don't support the nodejs16.x runtime, it does not make sense to allow the creation of Lambdas with Node.js 16 as target.

Are we able to look into supporting node 16? Node 14 is significantly out of date at this point, especially with the version of npm it ships with. Let me know if you need help with anything on this, happy to help. 

Thank you in advance! @ofhouse :D

**Comment by ofhouse** [comment]
Hey @nyt-larahelenaroth,

didn't noticed yet that Node.js 16 runtime was released to Lambda@Edge as well. Thanks for the reminder.

Upgrading should only have a small impact since it is only used by the router module.
The Next.js functions itself run on standard Lambdas that already support Node.js 16.

**Comment by larahroth** [comment]
@ofhouse Amazing! Thank you so much for replying & so glad to hear :D Please let us know timing so we can adjust once the support is deployed. Exciting news!
