### ISSUE TITLE
Examples do not work without version number being declared in main.tf

### ISSUE THREAD

**Issue by PodStuart** [milliHQ/terraform-aws-next-js#332]
I've been trying to follow some of your examples, namely "complete" and "atomic-deployments", and been getting various errors when following the instructions verbatim. I won't list the errors as I now understand why they were occurring. It is necessary to configure the appropriate version of the tf_next module in main.tf and then things work as expected. 

Perhaps this just needs a small update to the documentation. Happy to submit a PR for this myself. Perhaps it's super obvious and doesn't even need to be documented. I'm quite new to terraform.

**Comment by ofhouse** [comment]
Hi, thanks for the heads up on this 👍
The examples are a little behind for now, but will try to fix this soon!

Thing is that Terraform currently doesn't accept a version range for prerelease versions, e.g. `version = "~> 1.0.0-canary.4"` is not working, only exact versions are currently allowed: `version = "1.0.0-canary.4"`.
That means we have to ensure that the version in all examples is increased on each new prerelease.

Not a blocker because I think we can include this into our release pipeline pretty easily.
Also filled a bug report on Terraform, that version range on prereleases are currently not allowed: https://github.com/hashicorp/terraform/issues/31271
