### ISSUE TITLE
Updating existing alias does not appear to work

### ISSUE THREAD

**Issue by PodStuart** [milliHQ/terraform-aws-next-js#335]
I am using version 1.0.0-canary.4 and running `tf-next alias set <my alias> <deployment id> --force` to update an existing alias to point at a new deployment. However when I access my application the change is not being reflected. It feels like a cache somewhere has not been invalidated but I'm not entirely sure where.

**Comment by PodStuart** [comment]
I've tried a couple of things which have not worked.

1. Disabling browser caching.
2. Invalidating the Proxy-Config CloudFront distribution.

**Comment by PodStuart** [comment]
Manually changing the cache policy on the "Default (*)" behaviour on the "Main" CloudFront distribution to "Managed-CachingDisabled" appears to work around this issue.

**Comment by ofhouse** [comment]
Thanks for reporting.
Can confirm that the creation of invalidations is not working correctly in the latest canary release.
Currently evaluating different solutions to this problem since we plan to move from SQS to Lambda Step functions to handle the invalidation queue.
Since we have to handle multiple deployments, we now need a mechanism to deduplicate invalidations when they are enqueued.

An update to this is planned in one of the next releases.

**Comment by ruskeyz** [comment]
Is there a way to manually remove an alias?

`tf-next deployment rm <deployment-id> --force` 
doesn't work.  Same issue, /* invalidation of both CF distributions doesn't work as well

**Comment by david-vargas-blumer** [comment]
this problem persists
